# Generated by Django 5.1.3 on 2025-05-25 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_presence_start",
                    models.DateTimeField(verbose_name="زمان شروع حضور کاربر"),
                ),
                (
                    "user_presence_end",
                    models.DateTimeField(verbose_name="زمان انتهای حضور کاربر"),
                ),
                (
                    "user_presence_total",
                    models.PositiveIntegerField(verbose_name="مدت زمان حضور کاربر"),
                ),
                (
                    "canceled_visiting_time",
                    models.PositiveIntegerField(verbose_name="تعداد نوبت های کنسل شده"),
                ),
                (
                    "second_appointment",
                    models.BooleanField(
                        default=False, verbose_name="نوبت دوم گرفته / نگرفته"
                    ),
                ),
                (
                    "conversation_number",
                    models.PositiveIntegerField(verbose_name="تعداد گفت و گو ها"),
                ),
                (
                    "message_number",
                    models.PositiveIntegerField(verbose_name="تعداد پیام ها"),
                ),
                (
                    "media_message_number",
                    models.PositiveIntegerField(
                        verbose_name="تعداد گفت و گو های رسانه ای"
                    ),
                ),
                (
                    "text_message_number",
                    models.PositiveIntegerField(verbose_name="تعداد گفت و گو های متنی"),
                ),
                (
                    "visiting_time_message_number",
                    models.PositiveIntegerField(
                        verbose_name="تعداد پیام های مربوط به نوبت"
                    ),
                ),
                (
                    "cosultment_message_number",
                    models.PositiveIntegerField(
                        verbose_name="تعداد پیام های مربوط به مشاوره"
                    ),
                ),
                (
                    "profile_visit_number",
                    models.PositiveIntegerField(verbose_name="بازدید از پروفایل"),
                ),
                (
                    "profile_picture_visit_number",
                    models.PositiveIntegerField(verbose_name="بازدید از تصویر پروفایل"),
                ),
                (
                    "total_post_seen",
                    models.PositiveIntegerField(verbose_name="بازدید پست ها"),
                ),
                (
                    "total_story_seen",
                    models.PositiveIntegerField(verbose_name="بازدید استوری ها"),
                ),
                (
                    "no_story",
                    models.BooleanField(
                        default=False, verbose_name="کاربر بدون استوری"
                    ),
                ),
                (
                    "one_story",
                    models.BooleanField(
                        default=False, verbose_name="کاربر با یک استوری"
                    ),
                ),
                (
                    "more_than_one_story",
                    models.BooleanField(
                        default=False, verbose_name="کاربر با بیش از یک استوری"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "مانیتور کاربر",
                "verbose_name_plural": "مانیتور کاربر ها",
            },
        ),
        migrations.CreateModel(
            name="PostVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد لایک ها"
                    ),
                ),
                (
                    "monitoring_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_visits",
                        to="analyze_module.monitoringuser",
                        verbose_name="کاربر مانیتور شده",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="services_module.postmodel",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید پست",
                "verbose_name_plural": "بازدیدهای پست\u200cها",
                "unique_together": {("monitoring_user", "post")},
            },
        ),
        migrations.CreateModel(
            name="StoryVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد لایک ها"
                    ),
                ),
                (
                    "story_renewal",
                    models.BooleanField(default=False, verbose_name="تمدید استوری"),
                ),
                (
                    "monitoring_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_visits",
                        to="analyze_module.monitoringuser",
                        verbose_name="کاربر مانیتور شده",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="services_module.storymodel",
                        verbose_name="استوری",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید استوری",
                "verbose_name_plural": "بازدیدهای استوری ها",
                "unique_together": {("monitoring_user", "story")},
            },
        ),
    ]
