# Generated by Django 5.1.3 on 2025-05-25 01:14

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="نام تخفیف")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("holiday", "holiday"), ("admin", "admin")],
                        max_length=20,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                ("percentage", models.IntegerField(verbose_name="درصد تخفیف")),
                (
                    "start_date",
                    django_jalali.db.models.jDateTimeField(verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    django_jalali.db.models.jDateTimeField(verbose_name="تاریخ اتمام"),
                ),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیفات",
            },
        ),
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                (
                    "service_code",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="کد محصول"
                    ),
                ),
                (
                    "service_name_en",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="نام خدمت به انگلیسی",
                    ),
                ),
                (
                    "service_name_fa",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="نام خدمت به فارسی",
                    ),
                ),
                (
                    "service_icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="service_icons/",
                        verbose_name="تصویر لاین اصلی خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمت ها",
            },
        ),
        migrations.CreateModel(
            name="SliderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_picture",
                    models.FileField(
                        upload_to="slider_images/", verbose_name="تصویر اسلایدر"
                    ),
                ),
                (
                    "slider_text",
                    models.CharField(max_length=100, verbose_name="متن اسلایدر"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url_slider", models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدر ها",
            },
        ),
        migrations.CreateModel(
            name="TagsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=128, verbose_name="نام تگ")),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ ها",
            },
        ),
        migrations.CreateModel(
            name="HighlightModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ساخته شده در"
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات متن"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="highligh-thumbnail/",
                        verbose_name="پیش نمایش هایلایت",
                    ),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "هایلایت",
                "verbose_name_plural": "هایلایت ها",
            },
        ),
        migrations.CreateModel(
            name="HighlightSliderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(upload_to="highlights/media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="highligh-slider-thumbnail/",
                        verbose_name="پیش نمایش هایلایت",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                (
                    "highlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.highlightmodel",
                        verbose_name="هایلایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید هایلایت",
                "verbose_name_plural": "اسلاید های هایلایت",
            },
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="توضیحات متن")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ساخته شده در"
                    ),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد لایک ها"
                    ),
                ),
                (
                    "is_certificate",
                    models.BooleanField(default=False, verbose_name="گواهی نامه"),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="services_module.tagsmodel",
                        verbose_name="تگ ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست",
                "verbose_name_plural": "پست ها",
            },
        ),
        migrations.CreateModel(
            name="LikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.postmodel",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "لایک",
                "verbose_name_plural": "لایک\u200cها",
            },
        ),
        migrations.CreateModel(
            name="PostSliderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_file", models.FileField(upload_to="posts/media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.PositiveIntegerField(default=1)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post-thumbnail/",
                        verbose_name="پیش نمایش پست",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="services_module.postmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید پست",
                "verbose_name_plural": "اسلاید های پست",
            },
        ),
        migrations.CreateModel(
            name="SavedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان ذخیره شده"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.postmodel",
                        verbose_name="پست ذخیره شده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست ذخیره شده",
                "verbose_name_plural": "پست های ذخیره شده",
            },
        ),
        migrations.CreateModel(
            name="StoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "story_content",
                    models.FileField(
                        upload_to="stories/", verbose_name="محتوای استوری"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ساخته شده در"
                    ),
                ),
                (
                    "duration",
                    models.DateTimeField(auto_now_add=True, verbose_name="گذشته از"),
                ),
                ("reply", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "استوری",
                "verbose_name_plural": "استوری ها",
            },
        ),
        migrations.CreateModel(
            name="SupServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supservice_name_en",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="نام زیر خدمت به انگلیسی",
                    ),
                ),
                (
                    "supservice_name_fa",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="نام زیر خدمت به فارسی",
                    ),
                ),
                (
                    "supservice_icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="supservice_icons/",
                        verbose_name="تصویر زیر خدمت",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.servicemodel",
                        verbose_name="خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "زیر خدمت",
                "verbose_name_plural": "زیر خدمت ها",
            },
        ),
        migrations.CreateModel(
            name="UserServicesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_time",
                    models.PositiveIntegerField(verbose_name="زمان پیشنهادی خدمت"),
                ),
                (
                    "suggested_price",
                    models.PositiveIntegerField(
                        default=100000,
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="قیمت بیعانه",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.artistmodel",
                        verbose_name="هنرمند",
                    ),
                ),
                (
                    "supservice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code",
                        to="services_module.supservicemodel",
                        verbose_name="کد محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت هنرمند",
                "verbose_name_plural": "خدمات هنرمندان",
            },
        ),
        migrations.CreateModel(
            name="RankModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="مقدار امتیاز",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.artistmodel",
                        verbose_name="هنرمند",
                    ),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.userservicesmodel",
                        verbose_name="نام خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیاز ها",
            },
        ),
        migrations.CreateModel(
            name="VisitingTimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "صبح"),
                            ("noon", "ظهر"),
                            ("afternoon", "بعد از ظهر"),
                            ("evening", "عصر"),
                            ("night", "شب"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="زمان پیشنهادی",
                    ),
                ),
                (
                    "suggested_hour",
                    models.TimeField(
                        blank=True, null=True, verbose_name="ساعت پیشنهادی"
                    ),
                ),
                (
                    "suggested_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پیشنهادی"
                    ),
                ),
                (
                    "exact_time",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان دقیق نوبت"
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting for confirmation", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("waiting for deposit", "در انتظار بیعانه"),
                            ("completed", "تکمیل شده"),
                            ("deleted", "حذف شده"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="وضعیت نوبت",
                    ),
                ),
                (
                    "confirmation_time",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید"
                    ),
                ),
                (
                    "payment_due_time",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="مهلت پرداخت"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت بیعانه"
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="متن نظردهی"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.artistmodel",
                        verbose_name="هنرمند",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.rankmodel",
                        verbose_name="امتیاز دهی",
                    ),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.supservicemodel",
                        verbose_name="نام خدمت",
                    ),
                ),
                (
                    "unregistered_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.unregistereduser",
                        verbose_name="کاربر ثبت نام نشده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوبت دهی",
                "verbose_name_plural": "نوبت ها",
            },
        ),
        migrations.CreateModel(
            name="WalletModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف پول ها",
            },
        ),
    ]
