# Generated by Django 5.0.7 on 2024-08-08 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="نام تخفیف")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("holiday", "holiday"), ("admin", "admin")],
                        max_length=20,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                ("percentage", models.IntegerField(verbose_name="درصد تخفیف")),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ اتمام")),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیفات",
            },
        ),
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicesModel",
            fields=[
                (
                    "services_code",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="کد محصول"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=40, verbose_name="نام خدمت"),
                ),
                (
                    "suggested_time",
                    models.PositiveIntegerField(verbose_name="زمان پیشنهادی خدمت"),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمت ها",
            },
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_content",
                    models.FileField(upload_to="posts/", verbose_name="محتوای پست"),
                ),
                ("caption", models.TextField(blank=True, verbose_name="توضیحات متن")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ساخته شده در"
                    ),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد لایک ها"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست",
                "verbose_name_plural": "پست ها",
            },
        ),
        migrations.CreateModel(
            name="LikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.postmodel",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "لایک",
                "verbose_name_plural": "لایک\u200cها",
            },
        ),
        migrations.CreateModel(
            name="RankModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="مقدار امتیاز",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.artistmodel",
                        verbose_name="هنرمند",
                    ),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.servicesmodel",
                        verbose_name="نام خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیاز ها",
            },
        ),
        migrations.CreateModel(
            name="StoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "story_content",
                    models.FileField(
                        upload_to="stories/", verbose_name="محتوای استوری"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ساخته شده در"
                    ),
                ),
                (
                    "duration",
                    models.DateTimeField(auto_now_add=True, verbose_name="گذشته از"),
                ),
                ("reply", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "استوری",
                "verbose_name_plural": "استوری ها",
            },
        ),
        migrations.CreateModel(
            name="VisitingTimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "صبح"),
                            ("noon", "ظهر"),
                            ("afternoon", "بعد از ظهر"),
                            ("evening", "عصر"),
                            ("night", "شب"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="زمان پیشنهادی",
                    ),
                ),
                (
                    "suggested_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پیشنهادی"
                    ),
                ),
                (
                    "exact_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دقیق نوبت"
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting for confirmation", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("waiting for deposit", "در انتظار بیعانه"),
                            ("deleted", "حذف شده"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="وضعیت نوبت",
                    ),
                ),
                (
                    "confirmation_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید"
                    ),
                ),
                (
                    "payment_due_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مهلت پرداخت"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت بیعانه"
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="متن نظردهی"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.artistmodel",
                        verbose_name="هنرمند",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.rankmodel",
                        verbose_name="امتیاز دهی",
                    ),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                        verbose_name="سالن",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.servicesmodel",
                        verbose_name="نام خدمت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوبت دهی",
                "verbose_name_plural": "نوبت ها",
            },
        ),
        migrations.CreateModel(
            name="WalletModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف پول ها",
            },
        ),
    ]
