# Generated by Django 5.0.7 on 2024-08-10 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_module",
            "0003_remove_artistmodel_expertise_artistmodel_address_and_more",
        ),
        ("services_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_picture",
                    models.FileField(
                        upload_to="slider_images/", verbose_name="تصویر اسلایدر"
                    ),
                ),
                (
                    "slider_text",
                    models.CharField(max_length=100, verbose_name="متن اسلایدر"),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدر ها",
            },
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.artistmodel",
                verbose_name="artist",
            ),
        ),
        migrations.AddField(
            model_name="servicesmodel",
            name="saloon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.saloonmodel",
                verbose_name="saloon",
            ),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
