# Generated by Django 5.0.7 on 2024-08-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_module",
            "0003_remove_artistmodel_expertise_artistmodel_address_and_more",
        ),
        ("services_module", "0002_slidermodel_servicesmodel_artist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                (
                    "service_code",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="کد محصول"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=40, verbose_name="نام خدمت"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserServicesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_time",
                    models.PositiveIntegerField(verbose_name="زمان پیشنهادی خدمت"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.artistmodel",
                        verbose_name="artist",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name",
                        to="services_module.servicemodel",
                        verbose_name="نام خدمت",
                    ),
                ),
                (
                    "saloon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                        verbose_name="saloon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code",
                        to="services_module.servicemodel",
                        verbose_name="کد محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمت ها",
            },
        ),
        migrations.AlterField(
            model_name="rankmodel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services_module.userservicesmodel",
                verbose_name="نام خدمت",
            ),
        ),
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services_module.userservicesmodel",
                verbose_name="نام خدمت",
            ),
        ),
        migrations.DeleteModel(
            name="ServicesModel",
        ),
    ]
