# Generated by Django 5.0.7 on 2024-08-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0003_servicemodel_userservicesmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userservicesmodel",
            name="name",
        ),
    ]
