# Generated by Django 5.1.3 on 2024-12-25 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0005_highlightmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidermodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 12, 25, 5, 13, 16, 352016, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
