# Generated by Django 5.1.3 on 2024-12-31 22:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0006_slidermodel_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicemodel",
            options={"verbose_name": "خدمت", "verbose_name_plural": "خدمت ها"},
        ),
        migrations.RemoveField(
            model_name="userservicesmodel",
            name="saloon",
        ),
        migrations.RemoveField(
            model_name="userservicesmodel",
            name="service",
        ),
        migrations.AddField(
            model_name="userservicesmodel",
            name="suggested_price",
            field=models.PositiveIntegerField(
                default=100000,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(1000000),
                ],
                verbose_name="قیمت بیعانه",
            ),
        ),
        migrations.CreateModel(
            name="SupServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supservice_name",
                    models.CharField(max_length=128, verbose_name="نام زیر خدمت"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.servicemodel",
                        verbose_name="خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "زیر خدمت",
                "verbose_name_plural": "زیر خدمت ها",
            },
        ),
    ]
