# Generated by Django 5.1.3 on 2024-12-31 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0007_alter_servicemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userservicesmodel",
            options={
                "verbose_name": "خدمت هنرمند",
                "verbose_name_plural": "خدمات هنرمندان",
            },
        ),
        migrations.AddField(
            model_name="userservicesmodel",
            name="supservice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code",
                to="services_module.supservicemodel",
                verbose_name="کد محصول",
            ),
        ),
    ]
