# Generated by Django 5.1.3 on 2025-01-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0008_user_last_activity_time_user_total_active_time"),
        ("services_module", "0008_alter_userservicesmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemodel",
            name="service_icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="service_icons/",
                verbose_name="تصویر لاین اصلی خدمت",
            ),
        ),
        migrations.AlterField(
            model_name="userservicesmodel",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.artistmodel",
                verbose_name="هنرمند",
            ),
        ),
    ]
