# Generated by Django 5.1.3 on 2025-01-30 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0010_unregistereduser_alter_user_profile_picture"),
        ("services_module", "0009_servicemodel_service_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=128, verbose_name="نام تگ")),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ ها",
            },
        ),
        migrations.AddField(
            model_name="visitingtimemodel",
            name="unregistered_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.unregistereduser",
                verbose_name="کاربر ثبت نام نشده",
            ),
        ),
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="storymodel",
            name="tag",
            field=models.ManyToManyField(
                to="services_module.tagsmodel", verbose_name="تگ ها"
            ),
        ),
    ]
