# Generated by Django 5.1.3 on 2025-01-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services_module",
            "0010_tagsmodel_visitingtimemodel_unregistered_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicemodel",
            name="service_name",
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="service_name_en",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="نام خدمت به انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="service_name_fa",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="نام خدمت به انگلیسی"
            ),
        ),
    ]
