# Generated by Django 5.1.3 on 2025-01-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0011_remove_servicemodel_service_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storymodel",
            name="tag",
        ),
        migrations.AddField(
            model_name="postmodel",
            name="tag",
            field=models.ManyToManyField(
                to="services_module.tagsmodel", verbose_name="تگ ها"
            ),
        ),
    ]
