# Generated by Django 5.1.3 on 2025-02-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0012_remove_storymodel_tag_postmodel_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="service_name_fa",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="نام خدمت به فارسی"
            ),
        ),
    ]
