# Generated by Django 5.1.3 on 2025-02-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0013_alter_servicemodel_service_name_fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlightmodel",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات متن"),
        ),
    ]
