# Generated by Django 5.1.3 on 2025-02-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0014_highlightmodel_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supservicemodel",
            name="supservice_name",
        ),
        migrations.AddField(
            model_name="postmodel",
            name="is_certificate",
            field=models.BooleanField(default=False, verbose_name="گواهی نامه"),
        ),
        migrations.AddField(
            model_name="supservicemodel",
            name="supservice_icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="supservice_icons/",
                verbose_name="تصویر زیر خدمت",
            ),
        ),
        migrations.AddField(
            model_name="supservicemodel",
            name="supservice_name_en",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="نام زیر خدمت به انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="supservicemodel",
            name="supservice_name_fa",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="نام زیر خدمت به فارسی",
            ),
        ),
    ]
