# Generated by Django 5.1.3 on 2025-02-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0015_remove_supservicemodel_supservice_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitingtimemodel",
            name="suggested_hour",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت پیشنهادی"),
        ),
    ]
