# Generated by Django 5.1.3 on 2025-02-14 22:55

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0016_visitingtimemodel_suggested_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountmodel",
            name="end_date",
            field=django_jalali.db.models.jDateTimeField(verbose_name="تاریخ اتمام"),
        ),
        migrations.AlterField(
            model_name="discountmodel",
            name="start_date",
            field=django_jalali.db.models.jDateTimeField(verbose_name="تاریخ شروع"),
        ),
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="confirmation_time",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="زمان تایید"
            ),
        ),
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="exact_time",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="زمان دقیق نوبت"
            ),
        ),
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="payment_due_time",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="مهلت پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="suggested_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ پیشنهادی"
            ),
        ),
    ]
