# Generated by Django 5.1.3 on 2025-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0017_alter_discountmodel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waiting for confirmation", "در انتظار تایید"),
                    ("confirmed", "تایید شده"),
                    ("rejected", "رد شده"),
                    ("waiting for deposit", "در انتظار بیعانه"),
                    ("completed", "تکمیل شده"),
                    ("deleted", "حذف شده"),
                ],
                max_length=25,
                null=True,
                verbose_name="وضعیت نوبت",
            ),
        ),
    ]
