# Generated by Django 5.1.3 on 2025-02-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0018_alter_visitingtimemodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitingtimemodel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services_module.supservicemodel",
                verbose_name="نام خدمت",
            ),
        ),
    ]
