# Generated by Django 5.1.3 on 2025-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0019_alter_visitingtimemodel_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="services_module.tagsmodel",
                verbose_name="تگ ها",
            ),
        ),
    ]
