# Generated by Django 5.1.3 on 2025-03-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0016_saloonmodel_saloon_profile_picture"),
        ("services_module", "0020_alter_postmodel_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlightmodel",
            name="saloon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.saloonmodel",
            ),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="saloon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.saloonmodel",
            ),
        ),
        migrations.AddField(
            model_name="storymodel",
            name="saloon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.saloonmodel",
            ),
        ),
    ]
