# Generated by Django 5.1.3 on 2025-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0021_highlightmodel_saloon_postmodel_saloon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidermodel",
            name="url_slider",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
