# Generated by Django 5.1.3 on 2025-05-22 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0022_slidermodel_url_slider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="highlightmodel",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="highligh-thumbnail/",
                verbose_name="پیش نمایش هایلایت",
            ),
        ),
        migrations.AddField(
            model_name="storymodel",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="story-thumbnail/",
                verbose_name="پیش نمایش استوری",
            ),
        ),
        migrations.CreateModel(
            name="SavedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان ذخیره شده"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.postmodel",
                        verbose_name="پست ذخیره شده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست ذخیره شده",
                "verbose_name_plural": "پست های ذخیره شده",
            },
        ),
    ]
