# Generated by Django 5.1.3 on 2025-05-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services_module",
            "0023_highlightmodel_thumbnail_storymodel_thumbnail_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highlightmodel",
            name="highlight_content",
        ),
        migrations.RemoveField(
            model_name="postmodel",
            name="post_content",
        ),
        migrations.CreateModel(
            name="HighlightSliderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(upload_to="highlights/media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "highlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_module.highlightmodel",
                        verbose_name="هایلایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید هایلایت",
                "verbose_name_plural": "اسلاید های هایلایت",
            },
        ),
        migrations.CreateModel(
            name="PostSliderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_file", models.FileField(upload_to="posts/media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="services_module.postmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید پست",
                "verbose_name_plural": "اسلاید های پست",
            },
        ),
    ]
