# Generated by Django 5.1.3 on 2025-05-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_module", "0024_remove_highlightmodel_highlight_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storymodel",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="highlightslidermodel",
            name="position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="highlightslidermodel",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="highligh-slider-thumbnail/",
                verbose_name="پیش نمایش هایلایت",
            ),
        ),
        migrations.AddField(
            model_name="postslidermodel",
            name="position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="postslidermodel",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post-thumbnail/",
                verbose_name="پیش نمایش پست",
            ),
        ),
    ]
