# Generated by Django 5.1.3 on 2025-05-25 01:14

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=200)),
                ("attachment", models.FileField(blank=True, upload_to="")),
                (
                    "timestamp",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="RequestVisitNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=128, verbose_name="متن اعلان")),
                (
                    "timestamp",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("seen", models.BooleanField(default=False, verbose_name="دیده شده")),
            ],
        ),
    ]
