# Generated by Django 5.1.3 on 2025-03-05 05:39

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ChatAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
