# Generated by Django 5.1.3 on 2025-05-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatAPI", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="conversation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ChatAPI.conversation",
            ),
        ),
    ]
