# Generated by Django 5.1.3 on 2025-05-25 01:14

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnregisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره همراه"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="نام و نام خانوادگی"),
                ),
            ],
            options={
                "verbose_name": "کاربر ثبت نام نشده",
                "verbose_name_plural": "کاربران ثبت نام نشده",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره همراه"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="فعال / غیرفعال (0/1)"
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=6, null=True)),
                ("code_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, default="avatar.jpg", null=True, upload_to="Images/"
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[("سمنان", "سمنان")],
                        default="سمنان",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "birth_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ تولد"
                    ),
                ),
                ("public_key", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("online", "online"), ("offline", "offline")],
                        default="offline",
                        max_length=10,
                        null=True,
                        verbose_name="آنلاین / آفلاین (0/1)",
                    ),
                ),
                (
                    "total_active_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("last_activity_time", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="persons_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="persons_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
        migrations.CreateModel(
            name="NormalUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interests", models.TextField(verbose_name="علایق")),
                (
                    "normal_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normal_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر عادی",
                "verbose_name_plural": "کاربران عادی",
            },
        ),
        migrations.CreateModel(
            name="SaloonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام سالن")),
                ("management", models.CharField(max_length=255, verbose_name="مدیریت")),
                ("address", models.CharField(max_length=255, verbose_name="آدرس")),
                (
                    "saloon_rank",
                    models.CharField(
                        choices=[("A+", "A+"), ("A", "A"), ("B+", "B+"), ("B", "B")],
                        max_length=10,
                        verbose_name="رنک سالن",
                    ),
                ),
                (
                    "saloon_profile_picture",
                    models.ImageField(
                        blank=True, default="avatar.jpg", null=True, upload_to="Images/"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="طول جغرافیایی",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="عرض جغرافیایی",
                    ),
                ),
                (
                    "saloon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saloon",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سالن",
                "verbose_name_plural": "سالن\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ArtistModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years_of_work",
                    models.PositiveIntegerField(verbose_name="سال\u200cهای کار"),
                ),
                ("places_worked", models.TextField(verbose_name="مکان\u200cهای کار")),
                ("address", models.CharField(max_length=255, verbose_name="آدرس")),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saloon_artists",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_module.saloonmodel",
                        verbose_name="محل کار",
                    ),
                ),
            ],
            options={
                "verbose_name": "هنرمند",
                "verbose_name_plural": "هنرمندان",
            },
        ),
        migrations.CreateModel(
            name="ArtistFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دنبال کننده هنرمند",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="account_module.artistmodel",
                        verbose_name="هنرمند دنبال شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "دنبال شونده هنرمند",
                "verbose_name_plural": "دنبال شوندگان هنرمند",
                "unique_together": {("follower", "followed_user")},
            },
        ),
        migrations.CreateModel(
            name="NormalUserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normal_followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="account_module.normalusermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "دنبال شونده کاربر عادی",
                "verbose_name_plural": "دنبال شوندگان کاربر عادی",
                "unique_together": {("follower", "followed_user")},
            },
        ),
        migrations.CreateModel(
            name="SaloonFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saloon_followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دنبال کننده سالن",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="account_module.saloonmodel",
                        verbose_name="سالن دنبال شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "دنبال شونده سالن",
                "verbose_name_plural": "دنبال شوندگان سالن",
                "unique_together": {("follower", "followed_user")},
            },
        ),
    ]
