# Generated by Django 5.0.7 on 2024-08-08 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account_module", "0001_initial"),
        ("services_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistmodel",
            name="expertise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services_module.servicesmodel",
                verbose_name="تخصص",
            ),
        ),
        migrations.AddField(
            model_name="artistfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="account_module.artistmodel",
            ),
        ),
        migrations.AddField(
            model_name="normaluserfollow",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normal_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="normalusermodel",
            name="normal_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normal_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="normaluserfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="account_module.normalusermodel",
            ),
        ),
        migrations.AddField(
            model_name="saloonfollow",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saloon_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saloonmodel",
            name="saloon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saloon",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saloonfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="account_module.saloonmodel",
            ),
        ),
        migrations.AddField(
            model_name="artistmodel",
            name="saloon_artists",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account_module.saloonmodel",
                verbose_name="محل کار",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artistfollow",
            unique_together={("follower", "followed_user")},
        ),
        migrations.AlterUniqueTogether(
            name="normaluserfollow",
            unique_together={("follower", "followed_user")},
        ),
        migrations.AlterUniqueTogether(
            name="saloonfollow",
            unique_together={("follower", "followed_user")},
        ),
    ]
