# Generated by Django 5.0.7 on 2024-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistmodel",
            name="expertise",
        ),
        migrations.AddField(
            model_name="artistmodel",
            name="address",
            field=models.CharField(
                default="semnan", max_length=255, verbose_name="آدرس"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saloonmodel",
            name="address",
            field=models.CharField(
                default="semnan", max_length=255, verbose_name="آدرس"
            ),
            preserve_default=False,
        ),
    ]
