# Generated by Django 5.1.3 on 2024-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_module",
            "0003_remove_artistmodel_expertise_artistmodel_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="private_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
