# Generated by Django 5.1.3 on 2024-12-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0004_user_private_key_user_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
