# Generated by Django 5.1.3 on 2024-12-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0005_user_birth_date_user_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("online", "online"), ("offline", "offline")],
                default="offline",
                max_length=10,
                null=True,
                verbose_name="آنلاین / آفلاین (0/1)",
            ),
        ),
    ]
