# Generated by Django 5.1.3 on 2024-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0006_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="saloonmodel",
            name="saloon_rank",
            field=models.CharField(
                choices=[("A+", "A+"), ("A", "A"), ("B+", "B+"), ("B", "B")],
                default="A+",
                max_length=10,
                verbose_name="رنک سالن",
            ),
            preserve_default=False,
        ),
    ]
