# Generated by Django 5.1.3 on 2024-12-29 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0007_saloonmodel_saloon_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_active_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
