# Generated by Django 5.1.3 on 2025-01-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0008_user_last_activity_time_user_total_active_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="فعال / غیرفعال (0/1)"
            ),
        ),
    ]
