# Generated by Django 5.1.3 on 2025-01-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0009_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnregisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره همراه"
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="نام خانوادگی"),
                ),
            ],
            options={
                "verbose_name": "کاربر ثبت نام نشده",
                "verbose_name_plural": "کاربران ثبت نام نشده",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default/avatar.jpg/",
                null=True,
                upload_to="Images/",
            ),
        ),
    ]
