# Generated by Django 5.1.3 on 2025-02-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0010_unregistereduser_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistfollow",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دنبال کننده هنرمند",
            ),
        ),
        migrations.AlterField(
            model_name="artistfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="account_module.artistmodel",
                verbose_name="هنرمند دنبال شده",
            ),
        ),
        migrations.AlterField(
            model_name="saloonfollow",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saloon_followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دنبال کننده سالن",
            ),
        ),
        migrations.AlterField(
            model_name="saloonfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="account_module.saloonmodel",
                verbose_name="سالن دنبال شده",
            ),
        ),
    ]
