# Generated by Django 5.1.3 on 2025-02-14 22:55

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0011_alter_artistfollow_followed_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
    ]
