# Generated by Django 5.1.3 on 2025-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0012_alter_user_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unregistereduser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="unregistereduser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="unregistereduser",
            name="name",
            field=models.CharField(
                default=0, max_length=255, verbose_name="نام و نام خانوادگی"
            ),
            preserve_default=False,
        ),
    ]
