# Generated by Django 5.1.3 on 2025-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0013_remove_unregistereduser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
