# Generated by Django 5.1.3 on 2025-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0015_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="saloonmodel",
            name="saloon_profile_picture",
            field=models.ImageField(
                blank=True, default="avatar.jpg", null=True, upload_to="Images/"
            ),
        ),
    ]
