# Generated by Django 5.1.3 on 2025-03-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0016_saloonmodel_saloon_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="private_key",
        ),
    ]
