# Generated by Django 5.1.3 on 2025-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0017_remove_user_private_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="saloonmodel",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="saloonmodel",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
