# Generated by Django 5.1.3 on 2025-05-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0018_saloonmodel_latitude_saloonmodel_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saloonmodel",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="طول جغرافیایی",
            ),
        ),
        migrations.AlterField(
            model_name="saloonmodel",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="عرض جغرافیایی",
            ),
        ),
    ]
