# Generated by Django 5.1.3 on 2025-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0019_alter_saloonmodel_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[("سمنان", "سمنان")],
                default="سمنان",
                max_length=128,
                null=True,
            ),
        ),
    ]
